### ISSUE TITLE
Help and Docs

### ISSUE THREAD

**Issue by davidalexander** [tonyhb/store-optimizer#2]
Hi Tony
https://www.store-optimizer.com/help-and-docs seems to be unresponsive. Do you plan on adding this info into the repo or have an archive of it all? I'd be happy to help in reimplementing.

**Comment by tonyhb** [comment]
Hey David, 

Sure thing — planning on launching the site again this week with a link to the github repo. Documentation also definitely needs to be added to the wiki. Will close the issue once the site is launched (and maybe add it to github, too).

**Comment by davidalexander** [comment]
Wonderful. Thanks Tony.

**Comment by davidalexander** [comment]
Hi Tony
Any news on this? An archive of the old docs would be really useful if you're swamped.
Thanks.

**Comment by davidalexander** [comment]
Hi Tony
Any chance of some old docs? Any format would be useful.
Many thanks.
